name: Inf-Performance-Check 

on: 
  repository_dispatch:
    types: [test-python-workflow]
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps: 
      - name: echo parameters
        run: echo Client $CLIENT for Environment $ENV was chosen, Styles $STYLES"
        env: 
          CLIENT: ${{ github.event.client_payload.client }}
          ENV: ${{ github.event.client_payload.env }}
          STYLES: ${{ github.event.client_payload.env }}
      - name: echo python version
        run: echo python --version
