name: Inf-Performance-Check 

on: 
  repository_dispatch:
    types: [test-python-workflow]
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
        # Action 'checkout' clones the repo into the virtual-machine (working-space: name of repo)
      - name: checkout repo content
        uses: actions/checkout@v2
        # Action 'setup-python' helps to setup the correct python version
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute py script
        run: |
          pip install argparse
          python test.py -u $CLIENT -e $ENV -m $STYLES
        env: 
          CLIENT: ${{ github.event.client_payload.client }}
          ENV: ${{ github.event.client_payload.env }}
          STYLES: ${{ github.event.client_payload.styles }}
